### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by autodidaddict**
Updating wit for the batch interface

### CODE REVIEW

**Comment by Mossaka** [comment]
Thanks! Could you please rebase to the newest WIT syntax?

**Comment by autodidaddict** [comment]
Ok, the README should now match the newest wit files

**Comment by Mossaka** [comment]
BIg thanks for your prompt reply!! I will take a look at the interfaces today and send you some feedback

**Comment by autodidaddict** [comment]
I didn't change any of the interfaces.. I just updated the readme ;)

**Review by Mossaka — APPROVED** [review]
LGTM!

**Comment by Mossaka** [comment]
> I didn't change any of the interfaces.. I just updated the readme ;)

Ah my bad. Just approved it

**Pull request merged**
